### ISSUE TITLE
History page has <title>Login</title>

### ISSUE THREAD

**Issue by lannaa** [lannaa/web.test#16]
Open /History page 
Open view-source 
Note on page's title
<img width="768" alt="Screen Shot 2021-12-17 at 9 21 31 PM" src="https://user-images.githubusercontent.com/1503011/146599601-fce23055-6c49-4a73-aaf1-ff6de7d9ba46.png">

_ActuaI resuIt:_ 
<title>Login</title>

_Expected resuIt:_ 
<title>History</title>

**Comment by varajan** [comment]
Fixed. Please add an auto-test

**Comment by lannaa** [comment]
thank you, fixed
