### ISSUE TITLE
Minor cases 

### ISSUE THREAD

**Issue by lannaa** [lannaa/web.test#3]
1) Month 
Open Month dropdown 
Note how June month is displayed 
Actual result: June is displayed as "Jun"
Expected result: if all month have full form, then "Jun" should be "June"
<img width="390" alt="Screen Shot 2021-10-11 at 10 37 20 AM" src="https://user-images.githubusercontent.com/1503011/136751166-2069355e-6c9c-4a0c-9f40-1c6c2cc32116.png">

2) Opportunity to select Past date 
Open Year dropdown, note on years and select 1st year option
Actual result: it is possible to select past date, month, year 
Expected result: it is possible to select current or future date
<img width="318" alt="Screen Shot 2021-10-11 at 10 57 56 AM" src="https://user-images.githubusercontent.com/1503011/136753617-c2be151a-bce9-4acd-a589-0048a68f21b6.png">

3) Default Financial option 
Fill the calculator form except Financial year, note on interest earned value
Select 1st Financial year option, note on interest earned value
Then select 2d Financial year option, note on interest earned value
Again select 1st Financial year option, note on interest earned value

Actual result: Financial year is a mandatory field to be filled, and interest earned value is displayed without selecting Financial year option, using the default 365 option 

Expected result: If 365 option is default, then it should be selected by default 

<img width="507" alt="Screen Shot 2021-10-11 at 10 27 42 AM" src="https://user-images.githubusercontent.com/1503011/136752604-e57fb867-7d6d-4b6d-8a84-3ea52c77682a.png">
<img width="510" alt="Screen Shot 2021-10-11 at 10 27 03 AM" src="https://user-images.githubusercontent.com/1503011/136752627-03c2ab20-cb3a-40b0-ab21-32a80397d941.png">

**Comment by varajan** [comment]
Opportunity to select Past date -- works as designed.
